package com.example.maimaibackend.ticketsource.provider.enums;

public enum CallbackEventType {
    PROJECT_CHANGED, SESSION_CHANGED, TICKET_PRODUCT_CHANGED, INVENTORY_CHANGED, ORDER_CHANGED, TICKET_ISSUED, TICKET_VOIDED, REFUND_CHANGED, SHIPMENT_CHANGED, PROMOTION_CHANGED, CAMPAIGN_ASSET_CHANGED
}
